# Generated by Django 4.1.5 on 2023-03-18 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registered_user_delete_user'),
        ('socials', '0002_alter_socialslinks_vk_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soc_vars',
            fields=[
                ('registered_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vk_api_token', models.TextField(null=True, unique=True)),
                ('green_api_id', models.TextField(unique=True)),
                ('green_api_token', models.TextField(unique=True)),
                ('telegram_session_path', models.TextField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialsLinks',
        ),
    ]
